import type { Pattern, PatternType, TileData } from '../types';

/**
 * Base class for mosaic patterns
 * Provides common functionality and defines the pattern interface
 */
export abstract class BasePattern implements Pattern {
  abstract name: PatternType;

  /**
   * Sanitize URL to prevent CSS injection attacks
   * Validates and escapes URLs before use in background-image
   */
  protected sanitizeUrl(url: string): string {
    // Data URLs and blob URLs are safe (generated by browser)
    if (url.startsWith('data:') || url.startsWith('blob:')) {
      return url;
    }

    // Validate HTTP/HTTPS URLs
    if (url.startsWith('http://') || url.startsWith('https://')) {
      try {
        // URL constructor validates the URL format
        const validatedUrl = new URL(url);
        return validatedUrl.href;
      } catch {
        throw new Error(`Invalid image URL: ${url}`);
      }
    }

    // For relative paths, escape characters that could break CSS url()
    // Escape parentheses, quotes, and backslashes
    return url.replace(/[()'"\\]/g, '\\$&');
  }

  // Store container dimensions for background calculations
  protected containerWidth = 0;
  protected containerHeight = 0;

  /**
   * Generate tiles for this pattern
   */
  abstract generateTiles(
    containerWidth: number,
    containerHeight: number,
    cols: number,
    rows: number,
    gap: number
  ): TileData[];

  /**
   * Get container styles (can be overridden by patterns)
   */
  getContainerStyles(): Record<string, string> {
    return {
      position: 'relative',
      overflow: 'visible',
    };
  }

  /**
   * Get base tile styles
   * Uses pixel-based positioning for accurate image display
   */
  getTileStyles(
    tile: TileData,
    imageUrl: string,
    _cols: number,
    _rows: number
  ): Record<string, string> {
    return {
      position: 'absolute',
      left: `${tile.x}px`,
      top: `${tile.y}px`,
      width: `${tile.width}px`,
      height: `${tile.height}px`,
      'background-image': `url('${this.sanitizeUrl(imageUrl)}')`,
      // Use container size for background - image covers full mosaic
      'background-size': `${this.containerWidth}px ${this.containerHeight}px`,
      // Position background so this tile shows the correct portion
      'background-position': `-${tile.x}px -${tile.y}px`,
      'background-repeat': 'no-repeat',
      ...(tile.clipPath ? { 'clip-path': tile.clipPath } : {}),
    };
  }

  /**
   * Calculate background position for a tile (legacy - now using pixel positioning)
   */
  protected calculateBackgroundPosition(
    col: number,
    row: number,
    cols: number,
    rows: number
  ): { bgPosX: number; bgPosY: number } {
    const bgPosX = cols > 1 ? (col / (cols - 1)) * 100 : 0;
    const bgPosY = rows > 1 ? (row / (rows - 1)) * 100 : 0;
    return { bgPosX, bgPosY };
  }
}
